### ISSUE TITLE
nOt WoRkInG

### ISSUE THREAD

**Issue by CantRunRiver** [ABCxFF/diep-leftovers#2]
[drone_health.user.js](https://github.com/ABCxFF/diep-leftovers/blob/main/scripts/drone_health.user.js) is not working. and the screen freezes occasionally lol

**Comment by diepiodiscord** [comment]
Did the drone take damage, healthbars don't show anyway when they are at 100% health

**Comment by ABCxFF** [comment]
It literally says it won't work bro lol

**Comment by ABCxFF** [comment]
I won't give out any working drone health scripts
